Repository gustavosantaella/mobile-finance, pull requests merged in 2023-06, with the labels that each got.

#8 Dev
  lib/config/constanst.dart
  lib/helpers/fn/bottom_sheets.dart
  lib/helpers/fn/lang.dart
  lib/helpers/fn/main.dart
  lib/main.dart
  lib/pages/calendar/main.dart
  lib/pages/forgotPassword/ForgotPasswordChange.dart
  lib/pages/forgotPassword/ForgotPasswordCheckCode.dart
  lib/pages/forgotPassword/main.dart
  lib/pages/home/main.dart
  lib/pages/home/widgets/add_movment.dart
  lib/pages/home/widgets/balance.dart
  lib/pages/home/widgets/list_transaction_widget.dart
  lib/pages/home/widgets/transaction_container.dart
  lib/pages/list/main.dart
  lib/pages/login/main.dart
  lib/pages/profile/main.dart
  lib/pages/register/main.dart
  lib/pages/schedules/main.dart
  lib/providers/app_provider.dart
  lib/providers/drawe_provider.dart
  lib/providers/wallet_provider.dart
  lib/services/auth.dart
  lib/services/calendar.dart
  lib/services/country.dart
  lib/services/cron.dart
  lib/services/history.dart
  lib/services/home.dart
  lib/services/schedule.dart
  lib/services/user.dart
  lib/widgets/history_detail.dart
  lib/widgets/metric_container.dart
  lib/widgets/snack_bar.dart
  lib/widgets/splash_screen.dart
  pubspec.yaml
Labels: good first issue

#15 Features
  lib/helpers/fn/lang.dart
  lib/widgets/splash_screen.dart
Labels: bug

#23 issue 9
  lib/config/constanst.dart
  lib/helpers/fn/lang.dart
  lib/helpers/notifications/main.dart
  lib/pages/home/widgets/balance.dart
  lib/pages/profile/main.dart
  lib/providers/wallet_provider.dart
  lib/services/history.dart
  pubspec.lock
Labels: feature, pending to approve, finished, pending to deploy

#25 Issue 24
  lib/config/constanst.dart
  lib/helpers/fn/bottom_sheets.dart
  lib/helpers/fn/lang.dart
  lib/helpers/fn/main.dart
  lib/helpers/fn/norifications.dart
  lib/main.dart
  lib/pages/home/main.dart
  lib/pages/home/widgets/add_movment.dart
  lib/pages/home/widgets/transaction_container.dart
  lib/pages/loans/main.dart
  lib/pages/loans/new_loan_widget.dart
  lib/services/auth.dart
  lib/services/home.dart
  lib/services/loan.dart
  lib/widgets/card_widget.dart
  lib/widgets/categories_widget.dart
  lib/widgets/fn.dart
  lib/widgets/navigation_bar.dart
  lib/widgets/tag_widget.dart
Labels: feature
